version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
    network_mode: host
    volumes:
      - ./mqtt-init/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

